### PR TITLE
Fixes in 02-closures.md

### PR DESCRIPTION
**Pull request by resurtm**

### CODE REVIEW

**Comment by iliakan** [comment]
http://en.wikipedia.org/wiki/JavaScript uses "JavaScript"

What's the common agreement you are talking about?

**Comment by resurtm** [comment]
There was a discussion (i don't remember exactly where, maybe habrahabr.ru) about agreements of JS language title form which will be used in the book: "JavaScript" (first and fifth letters are uppercased), "Javascript" (only first letter is uppercased) or "javascript". All the three forms are widely used. I thought that you decided to use "Javascript" form, not "JavaScript". If this is not true, just decline second commit.

**Comment by iliakan** [comment]
Yeah, I pondered for a while, checked sources and found JavaScript most used. 

Feel free to prove I'm wrong by references. ;)

**Comment by resurtm** [comment]
No. Let's just use «JavaScript» form everywhere. :-)

**Comment by resurtm** [comment]
Okay. I've removed commit which replaces JavaScript to the Javascript. You can merge now.

**Pull request merged**
